#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MmViNWFmMjQ4ZmUwN2FjM2NmZTdlOTU4M2RjNWYzNmRkMWNkYzVhNDAxMzZiZjFmMDY2NDBmZTk1MTk2OGI3NjhkN2U4NDlmYjAxMGM2YzQ4MjRhZTAyNzkzNGQ1MDBhN2IyZA==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
